MediaMarkt Review System/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='review-home'),
    path('average/', views.average, name='review-average'),
    path('list', views.PersonListView.as_view(), name='person_changelist'),
    path('add/', views.PersonCreateView.as_view(), name='person_add'),
    path('<int:pk>/', views.PersonUpdateView.as_view(), name='person_change'),
    path('review/', views.review, name='review'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
    path('ajax/load-stores/', views.load_stores, name='ajax_load_stores'),
]

#    path('add/', views.PersonCreateView.as_view(), name='person_add'),

MediaMarkt Review System/django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='Register'),
    path('profile/', user_views.profile, name='Profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='Login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='Logout'),
    path('', include('blog.urls')),
    path('list/', RedirectView.as_view(pattern_name='person_changelist'), name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MediaMarkt Review System/blog/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.contrib.auth.models import User
from django.db.models import DateTimeField
from django.db.models.functions import Trunc


class Country(models.Model):
    name = models.CharField(max_length=30)
    class Meta:
        db_table="country"

    def __str__(self):
        return str(self.name)


class City(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    class Meta:
        db_table="city"

    def __str__(self):
        return str(self.name)


class Store(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    class Meta:
        db_table="store"

    def __str__(self):
        return str(self.name)


class Departments(models.Model):
    name = models.CharField(max_length=30)
    class Meta:
        db_table="departments"

    def __str__(self):
        return str(self.name)

class Ratings(models.Model):
    rating = models.CharField(max_length=30)
    class Meta:
        db_table="rating"

    def __str__(self):
        return str(self.rating)




class Review(models.Model):
    name = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE)
    #user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)
    store = models.ForeignKey(Store, on_delete=models.SET_NULL, null=True)
    department = models.ForeignKey(Departments, on_delete=models.SET_NULL, null=True)
    rating = models.ForeignKey(Ratings, on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return str(self.name)

MediaMarkt Review System/blog/forms.py
from django import forms
from .models import Review, City, Store


class PersonForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('country', 'city','store','department', 'rating')


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['city'].queryset = City.objects.none()

        if 'country' in self.data:
            try:
                country_id = int(self.data.get('country'))
                self.fields['city'].queryset = City.objects.filter(country_id=country_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.country.city_set.order_by('name')
 
#Stores
        self.fields['store'].queryset = City.objects.none()
        if 'city' in self.data:
            try:
                city_id = int(self.data.get('city'))
                self.fields['store'].queryset = Store.objects.filter(city_id=city_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            #self.fields['vanue'].queryset = self.instance.country.city.vanue_set.order_by('name')
            self.fields['store'].queryset = self.instance.city.store_set.order_by('name')

MediaMarkt Review System/blog/views.py
import sqlite3
from pyexpat import model
from typing import List
from unicodedata import name
from urllib import request
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.utils.decorators import method_decorator
from django.shortcuts import render
from django.contrib import messages
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.db import connection


from .models import Review, City, Store
from .forms import PersonForm


def home(request):
    return render(request, 'blog/home.html',{'title': 'Homepage'})

#def about(request):
    return render(request, 'blog/about.html', {'title': 'About'})


def review(request):
    return render(request,'blog/review.html', {'title': 'Review'})


class PersonListView(LoginRequiredMixin, ListView):
    model = Review
    context_object_name = 'people'
    ordering = ['-date']




class PersonCreateView(LoginRequiredMixin, CreateView):
    model = Review
    form_class = PersonForm
    success_url = reverse_lazy('person_changelist')
    

    def form_valid(self,form):
        form.instance.name = self.request.user
        return super(PersonCreateView,self).form_valid(form)

    def form_valid(self, form):
        form.instance.name = self.request.user
        return super().form_valid(form)


class PersonUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Review
    form_class = PersonForm
    success_url = reverse_lazy('person_changelist')

    def form_valid(self,form):
        form.instance.name = self.request.user
        return super(PersonUpdateView,self).form_valid(form)

    def test_func(self):
        Review = self.get_object()
        if self.request.user == Review.name:
            return True
        return False


def load_cities(request):
    country_id = request.GET.get('country')
    cities = City.objects.filter(country_id=country_id).order_by('name')
    return render(request, 'blog/city_dropdown_list_options.html', {'cities': cities})


def load_stores(request):
    city_id = request.GET.get('city')
    stores = Store.objects.filter(city_id=city_id).order_by('name')
    return render(request, 'blog/storedropdown.html', {'stores': stores})



def average(request):
        connection = sqlite3.connect('Mediamarkt.db')
        cursor = connection.cursor()
        print("Connected to SQLite")

        sqlite_select_query = """select name, avg(rating_id) from blog_review 
                                join city 
                                on blog_review.city_id = city.id
                                group by name, blog_review.city_id """

        cursor.execute(sqlite_select_query)
        records = cursor.fetchall()
        connection.commit()
        connection.close

        ##Store
        connection = sqlite3.connect('Mediamarkt.db')
        cursor = connection.cursor()
        print("Connected to SQLite")

        sqlite_q = """SELECT name, avg(rating_id) from blog_review 
                        join store 
                        on blog_review.store_id = store.id
                        group by name, blog_review.store_id"""

        cursor.execute(sqlite_q)
        records2 = cursor.fetchall()
        connection.commit()
        connection.close

        ##Department
        connection = sqlite3.connect('Mediamarkt.db')
        cursor = connection.cursor()
        print("Connected to SQLite")

        sqlite_q = """select name, avg(rating_id) from blog_review 
                        join departments
                        on blog_review.department_id = departments.id
                        group by name, blog_review.department_id"""

        cursor.execute(sqlite_q)
        records3 = cursor.fetchall()
        connection.commit()
        connection.close


        return render(request,'blog/average_list.html',{'data2': records2, 'data': records, 'data3': records3}) 

MediaMarkt Review System/blog/templates/blog/average_list.html
{% extends "blog/base.html"%}
{% block content %}

<form id="average" action="/list" method="get" target="_blank">
    <button class="mainbutton4" type="">Rewiews List</button>
 </form>
 <form id="average" action="/add" method="get" target="_blank">
    <button class="mainbutton4" type="">Add a review</button>
 </form>
 <br> <br>
<div class="" id="rating_list">
    <h3>Average rating for Cities</h3>
    <div class="content-section">
        <table id="table_list">
            <tr> 
                <th id="th_list">City</th>
                <th id="th_list">Average rating</th>
            </tr>
                {% for row0 in data %} 
            <tr>                        
                <td id="td_list">{{ row0.0 }}</td>
                <td id="td_list">{{ row0.1 }}</td>
                    {% endfor %}
            </tr>
        </table>
    </div>
    <br>
    <h3>Average rating for Stores</h3>
    <div class="content-section">
        <table id="table_list">
            <tr> 
                <th id="th_list">Store</th>
                <th id="th_list">Average rating</th>
            </tr>
                {% for row0 in data2 %} 
            <tr>                        
                <td id="td_list">{{ row0.0 }}</td>
                <td id="td_list">{{ row0.1 }}</td>
                    {% endfor %}
            </tr>
        </table>
    </div>
    <br>
    <h3>Average rating for Departments</h3>
    <div class="content-section">
        <table id="table_list">
            <tr> 
                <th id="th_list">Department</th>
                <th id="th_list">Average rating</th>
            </tr>
                {% for row0 in data3 %} 
            <tr>                        
                <td id="td_list">{{ row0.0 }}</td>
                <td id="td_list">{{ row0.1 }}</td>
                    {% endfor %}
            </tr>
        </table>
    </div>
</div>
{% endblock content %}

MediaMarkt Review System/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">

    

    {% if title %}
        <title>Mediamarkt Review- {{title}}</title> 
    {% else %}
        <title>Mediamarkt Review</title> 
    {%endif%}
    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-lg bg-steel fixed-top">
        <style> 
          .navbar {
            box-shadow: 0px 2px 5px #777
        } </style>
        <a class="navbar-brand" href="/"><img src="https://upload.wikimedia.org/wikipedia/commons/f/f0/Media_Markt_logo.svg" width="150  " height="50" alt="" ></a>
      
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-item nav-link" target="_blank" href="http://www.mediamarkt.com">Official Website</a>
            </li>
           
            
          </ul>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'Profile' %}">Profile</a>
                <a class="nav-item nav-link" href="{% url 'Logout' %}">Logout</a>
                {% else %}
                  <a class="nav-item nav-link" href="{% url 'Login' %}">Login</a>
                  <a class="nav-item nav-link" href="{% url 'Register' %}">Register</a>
                {% endif %}
              </div>          
        </div>
      </nav>
    </header>
      <main role="main" class="container">
        <div class="row">
          <div class="">
            {% if messages %}
              {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
          </div>
          <div class="col-md-4">
          
          </div>
        </div>
      </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

MediaMarkt Review System/blog/templates/blog/city_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

MediaMarkt Review System/blog/templates/blog/home.html
{% extends "blog/base.html"%}
{% block content %}

<!DOCTYPE html>
<html>
<head>

</head>

<body>
    <div>
        <div class="main">
            <h1 style=""> <b> Welcome to the MediaMarkt Service Quality Review System</b> </h1>
            <form action="add/" method="get" target="_blank">
                <button class="mainbutton btn btn-primary btn-lg" type="submit">Submit a Review</button>
             </form>
        </div>
    </div>
    <div class="main2">
        <p class="maintext"> Please click on the <b> Submit a Review</b> button to review MediaMarkt Departments.</p>
        <p class="maintext"> <b><a href="{% url 'person_add' %}">Review submission</a></b> and <b><a href="{% url 'person_changelist' %}">Review list</a></b> are only available for the <b> registered </b> users. You will be required to <b><a href="{% url 'Login' %}">log in</a></b> to your account.</p>
        <p class="maintext"> Unregistrated visitors may see <b><a href="{% url 'review-average' %}">Mediamarkt rating</a></b> by <b>city</b>, <b>store</b> and <b>department</b> based on customer reviews.</p>
    </div>
    
</body>

</html>
{% endblock content %}

MediaMarkt Review System/blog/templates/blog/review.html
{% extends "blog/base.html"%}
{% block content %}

<!DOCTYPE html>

<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="/path/to/cdn/jquery.slim.min.js">
  </script>
  <script src="jquery.chained.selects.js"></script>
  <script>
    $(document).ready(function()
    {
      var $countryvar=$("#country");
          $cityvar=$("#city");
  
          $options=$cityvar.find('option');
          $countryvar.on('change', function()
          {
            $cityvar.html($options.filter('[value="'+this.value+'"]'));
          }).trigger('change');
    });
  </script>
</head>
<body>
  <div class="" id="content1">
    <div class="content-section">
      <form action="">

        <select id="country">
          <option disabled selected="true"> Select a country </option> 
          {% for country in Countrydata %}
          <option value="{{country.id_country}}">{{country.Name}}</option>
          {% endfor %}
        </select>
        <br><br>
        <select id="city" >
          <option disabled selected="true"> Select a city </option> 
          {% for city in Citydata %}
          <option value="{{city.id_country}}">{{city.Name}}</option>
          {% endfor %}
        </select>
        <br><br>
        <input class="btn btn-primary" type="submit" value="Search">
        
      </form>
    </div>
  </div>
</body>

{% endblock content %}

MediaMarkt Review System/blog/templates/blog/review_form.html
{% extends "blog/base.html"%}

{% block content %}
  <div class="" id="content4">
    <div class="content-section">
      <h2 > Mediamarkt Review Form</h2>

      <div class="main3">
          <br>
          Please, select the respective <b>"Country"</b>, <b>"City"</b>,<b>"Store"</b> and <b>Submit</b> your review.
          <br>
        </p>
      </div>

      <form method="post" id="personForm" data-cities-url="{% url 'ajax_load_cities' %}" novalidate>
        {% csrf_token %}
        <table>
          {{ form.as_table }}
        </table>
        <br> <br>
        <button class="mainbutton2" type="submit">Submit</button>
        <button class="mainbutton2" type="reset" value="Reset">Reset</button>
        <br> <br>
      </form>
          <br>
          <div class="main2">
            <b class="">Just want to see the reviews?</b>
          </div>
          <br>
      <form action="/list" method="get" target="_blank">
        <button class="mainbutton3" type="">Rewiews List</button>
     </form>
    

      <script>
        $("#id_country").change(function () {
          var url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view
          var countryId = $(this).val();  // get the selected country ID from the HTML input
    
          $.ajax({                       // initialize an AJAX request
            url: '{% url 'ajax_load_cities' %}',                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
            data: {
              'country': countryId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
              $("#id_city").html(data);  // replace the contents of the city input with the data that came from the server
            }
          });
    
        });
        // this one is for fetching vanue data
        $("#id_city").change(function () { //django-model-form created this id
          var url = $("#personForm").attr("data-stores-url");  // get the url of the `load_cities` view
          var cityId = $(this).val();  // get the selected country ID from the HTML input
    
          $.ajax({                       // initialize an AJAX request
            url: '{% url 'ajax_load_stores' %}',                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/) person_form.html template has this url var
            data: {
              'city': cityId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
              $("#id_store").html(data);  // replace the contents of the city input with the data that came from the server
            }
          });
    
        });
      </script>
    </div>
  </div>

{% endblock %}

MediaMarkt Review System/blog/templates/blog/review_list.html
{% extends "blog/base.html"%}

{% block title %}{% endblock %}

{% block content %}
<meta name="viewport" content="width=device-width, initial-scale=1">

  <div class="" id="rating_list">
    <div class="content-section">
    <p>
      <form id="review_list" action="/add" method="get" target="_blank">
        <button class="mainbutton4" type="">Add a Review</button>
     </form>
    </p>
    <br>
    <p class="review_list_text">
      Only the review authors may <b>change/edit</b> their reviews by clicking on their names.
    </p>
    <p class="review_list_text3">
      Users are not allowed to delete the reviews due to the transparency. Please, contact to <b>admin@mmrewiew.com</b>.
    </p>
    <p class="review_list_text2">Check <b><a href="{% url 'review-average' %}">Mediamarkt rating</a></b> by <b>city</b>, <b>store</b> and <b>department</b>.</p>
    <table id="table_list">
      <thead>
        <tr>
          <th id="th_list">Name</th>
          <th id="th_list">Country</th>
          <th id="th_list">City</th>
          <th id="th_list">Store</th>
          <th id="th_list">Department</th>
          <th id="th_list">Rating</th>
        </tr>
      </thead>
      <tbody>
        {% for person in people %}
          <tr>
            <td id="td_list"><a href="{% url 'person_change' person.pk %}">{{ person.name }}</a></td>
            <td id="td_list">{{ person.country.name }}</td>
            <td id="td_list">{{ person.city.name }}</td>
            <td id="td_list">{{ person.store.name }}</td>
            <td id="td_list">{{ person.department.name }}</td>
            <td id="td_list">{{ person.rating.rating }}</td>
          </tr>
        {% empty %}
          <tr>
            <td colspan="4">There is no review in the system!</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

MediaMarkt Review System/blog/templates/blog/storedropdown.html
<option value="">---------</option>
{% for store in stores %}
<option value="{{ store.pk }}">{{ store.name }}</option>
{% endfor %}